#+title: emacs.d

The Emacs configuration directory.

Place this directory so that Emacs can find the ~init.el~ file. The auxiliary scripts used by Emacs is placed under the ~bin/~ directory.

* Convention
** ~straight-use-package~

The ~init.el~ is organized using ~use-package~ with ~straight~.

*** Initializing a built-in package

Use ~:straight nil~ to avoid pulling the source:

#+begin_src elisp
  (use-package builtin-package
    :straight nil
    …)
#+end_src

** Use of ~init-loader~

Package initialization files are in the ~lisp/~ directory. The files actually loaded are symlinked in the ~init.d~ directory and loaded by the ~init-loader~ package. The files are sorted by file name and loaded in that  order.

Run

#+begin_src shell
  init.d/symlinks.sh
#+end_src

to create symlinks under the ~init.d/~ directory.

** Key bindings

See the [[info:elisp#Key Binding Conventions][Key Binding Conventions]] section of the GNU Emacs Lisp Reference Manual.

* Improving startup time

In Linux systems, the startup time for this Emacs initialization takes 1.5 - 2.0 seconds.

The ~find-at-startup~ option is removed from  ~straight-check-for-modifications~; see ~lisp/traight-use-package.el~ for caveat.

While the ~init.el~ in this repository is written primarily with readability and maintainability in mind, it pays well to be aware of improvement we can make with the startup time.

  - [[https://emacs-jp.github.io/tips/startup-optimization][Emacs の起動時間を”“詰める”” | Emacs JP]]
  - [[https://zenn.dev/zk_phi/books/cba129aacd4c1418ade4][Emacs の起動時間を""詰める""]] (free book version)
