#+title: emacs.d

The Emacs configuration directory.

Place this directory so that Emacs can find the ~init.el~ file. The auxiliary scripts used by Emacs is placed under the ~bin/~ directory.

* Convention
** ~straight-use-package~

The ~init.el~ is organized using ~use-package~ with ~straight~.

*** Initializing a built-in package

Use ~:straight nil~ to avoid pulling the source:

#+begin_src elisp
  (use-package builtin-package
    :straight nil
    …)
#+end_src

** Use of ~init-loader~

Package initialization files are in the ~lisp/~ directory. The files actually loaded are symlinked in the ~init.d~ directory and loaded by the ~init-loader~ package. The files are sorted by file name and loaded in that  order.

Run

#+begin_src shell
  init.d/symlinks.sh
#+end_src

to create symlinks under the ~init.d/~ directory.

** Key bindings

See the [[info:elisp#Key Binding Conventions][Key Binding Conventions]] section of the GNU Emacs Lisp Reference Manual.

* Improving startup time

In Linux systems, the startup time for this Emacs initialization takes 1.5 - 2.0 seconds.

The ~find-at-startup~ option is removed from  ~straight-check-for-modifications~; see ~lisp/traight-use-package.el~ for caveat.

While the ~init.el~ in this repository is written primarily with readability and maintainability in mind, it pays well to be aware of improvement we can make with the startup time.

  - [[https://emacs-jp.github.io/tips/startup-optimization][Emacs の起動時間を”“詰める”” | Emacs JP]]
  - [[https://zenn.dev/zk_phi/books/cba129aacd4c1418ade4][Emacs の起動時間を""詰める""]] (free book version)

* init.el repositories

Over the years, my Emacs init.el has been inspired by numerous sources, some of which are listed here in no particular order:

  - https://github.com/abougouffa/minemacs
      - See docs/EXTERNAL-TOOLS.md
  - https://github.com/freetonik/emacs-dotfiles/blob/master/init.el
  - https://github.com/jamescherti/minimal-emacs.d
  - https://github.com/kwpav/dotfiles/blob/master/emacs.org
  - https://github.com/progfolio/.emacs.d/
  - https://github.com/purcell/emacs.d
  - https://github.com/trev-dev/emacs
  - https://github.com/vedang/emacs-up
  - https://gitlab.com/nathanfurnal/dotemacs/-/blob/master/init.el
  - https://protesilaos.com/emacs/dotemacs
  - https://sachachua.com/dotemacs/index.html
  - https://takaxp.github.io/init.html
  - [[https://gist.github.com/axyz/76871b404df376271b521212fba8a621][axyz/early-init.el]]
  - The =reading-init-el= channel at emacs-jp.slack.com
