#+title: emacs.d

An Emacs configuration directory.

* Introduction

This version-controlled repository acts as the main configuration for a local installation of Emacs.

** Repository Structure

#+begin_example
  emacs.d/
  ├─ bin/                - Shell scripts (add to PATH)
  ├─ etc/                - Package startup configs
  │  └─ tempel/          - `tempel' templates
  ├─ init.d/             - Symlinks to sources used during init
  │  └─ symlinks.sh      - The init.d admin script
  ├─ lisp/               - Emacs Lisp package source files
  │  ├─ archive/         - Unused code archive
  │  ├─ themes/          - Theme package config files
  │  │  └─ themes-*.el   - Configure a theme
  │  ├─ init-*.el        - Configure a package during init
  │  ├─ linux-gui.el     - Configure Linux GUI sub-component
  │  ├─ maj-*.el         - Configure a major mode & its utilities
  │  ├─ optimizations.el - Optimizations configured during init
  │  └─ subsys-*.el      - Configure a non-major-mode subsystem
  ├─ straight/           - Used by `straight'
  │  ├─ repos/           - Package sources
  │  └─ versions/
  │     └─ default.el    - Version freeze info
  ├─ tree-sitter/        - Tree-sitter libraries
  ├─ var/                - Package data
  ├─ early-init.el
  └─ init.el
#+end_example

The Emacs starts by loading =early-init.el= and then =init.el=, within which ~init-loader~ reads sources from =init.d=. The config units are organized with ~use-package~ with ~straight~.

*** ~use-package~ and ~straight~

The configuration =lisp/init-straight.el= set up ~use-package~ to pull packages using ~straight~. All straight recipes are set up in this file to remove the need for using the ~:straight~ keyword in each ~use-package~ form. In the same configuration file, explicitly list packages to ensure the use of built-in version over externally available one to avoid conflict.

*** ~init-loader~

The ~init-loader~ runs toward the end of ~init.el~. The Emacs Lisp sources in the directory =init.d/= are loaded and executed in order of priority based on file name (roughly ASCII).

The Emacs Lisp files in =init.d/= are symlinked from the directory =lisp/= to allow selective loading of Emacs Lisp packages for modular configurations. Symlinking managed by the =init.d/symlinks.sh= shell script:

#+begin_src shell
  ./init.d/symlinks.sh -r  # refresh all symlinks
#+end_src

** Miscellaneous Topics

See the [[https://github.com/okomestudio/emacs.d/wiki][repository wiki]] for miscellaneous or faster changing topics.

* Installation

Clone the repository root to a path within the filesystem where Emacs can find the =init.el= file, e.g. =~/.config/emacs=.
