#+title: emacs.d

The Emacs configuration directory.

Place this directory so that Emacs can find the ~init.el~ file. The auxiliary scripts used by Emacs is placed under the ~bin/~ directory.

* Convention
** ~straight-use-package~

The ~init.el~ is organized using ~use-package~ with ~straight~.

*** Initializing a built-in package

Use ~:straight nil~ to avoid pulling the source:

#+begin_src elisp
  (use-package builtin-package
    :straight nil
    …)
#+end_src

** Use of ~init-loader~

Most package initialization files are in the ~init.d~ directory. The ~init-loader~ packer allows the better management of package loading order by file name.

** Key bindings

See the [[info:elisp#Key Binding Conventions][Key Binding Conventions]] section of the GNU Emacs Lisp Reference Manual.

* Improving startup time

In Linux systems, the startup time for the Emacs initialization in this repo is no more than 2 to 5 seconds. With the current paradigm, I haven’t been able to improve further, unless I’m willing to go without ~use-package~ and disable a few major features that I’d need to use.

While the ~init.el~ in this repository is written primarily with readability and maintainability in mind, it pays well to be aware of improvement we can make with the startup time.

  - [[https://emacs-jp.github.io/tips/startup-optimization][Emacs の起動時間を”“詰める”” | Emacs JP]]
  - [[https://zenn.dev/zk_phi/books/cba129aacd4c1418ade4][Emacs の起動時間を""詰める""]] (free book version)

* Packages to check out

- [[https://github.com/Wilfred/emacs-refactor][emr]] (Emacs Refactor)
    - A framework for providing language-specific refactoring
- [[https://github.com/ahyatt/llm][llm]]
    - A package abstracting llm capabilities
- [[https://github.com/emacs-jp/migemo][migemo]]
    - Provides incremental search with romanized Japanese
- [[https://github.com/emacsmirror/password-store][password-store]]
    - Allows ~pass~ integration for managing credentials
- [[https://github.com/a13/reverse-im.el][reverse-im.el]]
    - Overrides ~function-key-map~ for preferred input method(s) to translate input sequences to English, so we can use emacs binding while a non-default system layout is active
- [[https://github.com/captainflasmr/selected-window-accent-mode][selected-window-accent-mode]]
    - Accentuate the active window
- [[https://github.com/WJCFerguson/textsize/][textsize]]
    - Automatically choose a font point size for the Emacs default face based on the size and pixel pitch of the display
- [[https://github.com/m00natic/vlfi][vlf]]
    - View large files

* init.el repositories

Over the years, my Emacs init.el has been inspired by numerous sources, some of which are listed here in no particular order:

  - https://github.com/abougouffa/minemacs
      - See docs/EXTERNAL-TOOLS.md
  - https://github.com/freetonik/emacs-dotfiles/blob/master/init.el
  - https://github.com/jamescherti/minimal-emacs.d
  - https://github.com/kwpav/dotfiles/blob/master/emacs.org
  - https://github.com/progfolio/.emacs.d/
  - https://github.com/purcell/emacs.d
  - https://github.com/trev-dev/emacs
  - https://github.com/vedang/emacs-up
  - https://gitlab.com/nathanfurnal/dotemacs/-/blob/master/init.el
  - https://protesilaos.com/emacs/dotemacs
  - https://sachachua.com/dotemacs/index.html
  - https://takaxp.github.io/init.html
  - The =reading-init-el= channel at emacs-jp.slack.com
