#+title: emacs.d

The Emacs configuration directory.

Place this directory so that Emacs can find the ~init.el~ file. The auxiliary scripts used by Emacs is placed under the ~bin/~ directory.

* Convention
** ~straight-use-package~

The ~init.el~ is organized using ~use-package~ with ~straight~.

*** Initializing a built-in package

Use ~:straight nil~ to avoid pulling the source:

#+begin_src elisp
  (use-package builtin-package
    :straight nil
    …)
#+end_src

** Use of ~init-loader~

Most package initialization files are in the ~init.d~ directory. The ~init-loader~ packer allows the better management of package loading order by file name.

* Packages to check out

- [[https://github.com/Wilfred/emacs-refactor][emr]] (Emacs Refactor)
    - A framework for providing language-specific refactoring
- [[https://github.com/emacsmirror/password-store][password-store]]
    - Allows ~pass~ integration for managing credentials
- [[https://github.com/a13/reverse-im.el][reverse-im.el]]
    - Overrides ~function-key-map~ for preferred input method(s) to translate input sequences to English, so we can use emacs binding while a non-default system layout is active
- [[https://github.com/m00natic/vlfi][vlf]]
    - View large files

* Reference init.el repositories

Over the years, my Emacs init.el has been inspired by numerous sources, some of which are listed here in no particular order:

  - https://github.com/freetonik/emacs-dotfiles/blob/master/init.el
  - https://github.com/jamescherti/minimal-emacs.d
  - https://github.com/kwpav/dotfiles/blob/master/emacs.org
  - https://github.com/purcell/emacs.d
  - https://github.com/trev-dev/emacs
  - https://github.com/vedang/emacs-up
  - https://gitlab.com/nathanfurnal/dotemacs/-/blob/master/init.el
  - https://protesilaos.com/emacs/dotemacs
  - https://sachachua.com/dotemacs/index.html
  - https://takaxp.github.io/init.html
  - The =reading-init-el= channel at emacs-jp.slack.com
