#+title: emacs.d

An Emacs configuration directory.

* Introduction

This version-controlled repository acts as the main configuration for a local installation of Emacs.

** Repository Structure

#+begin_example
  emacs.d/
  ├─ bin/                - Shell scripts (add to PATH)
  ├─ etc/                - Package startup configs
  │  └─ tempel/          - `tempel' templates
  ├─ init.d/             - Symlinks to sources loaded by `init-loader'
  │  ├─ <unit>/          - `init-loader' unit
  │  ├─ unit-<unit>.sh   - `init-loader' unit definition
  │  └─ symlinks.sh      - `init-loader' admin script
  ├─ lisp/               - Emacs Lisp package source files
  │  ├─ archive/         - Unused code archive
  │  ├─ themes/          - Theme package config files
  │  │  └─ themes-*.el   - Configure a theme
  │  ├─ init-*.el        - Configure a package during init
  │  ├─ linux-gui.el     - Configure Linux GUI sub-component
  │  ├─ maj-*.el         - Configure a major mode & its utilities
  │  ├─ optimizations.el - Optimizations configured during init
  │  └─ subsys-*.el      - Configure a non-major-mode subsystem
  ├─ straight/           - Used by `straight'
  │  ├─ repos/           - Package sources
  │  └─ versions/
  │     └─ default.el    - Version freeze info
  ├─ tree-sitter/        - Tree-sitter libraries
  ├─ var/                - Package data
  ├─ early-init.el
  └─ init.el
#+end_example

The Emacs starts by loading =early-init.el= and then =init.el=, within which ~init-loader~ reads sources from =init.d=. The config units are organized with ~use-package~ with ~straight~.

*** ~use-package~ and ~straight~

The configuration =lisp/init-straight.el= set up ~use-package~ to pull packages using ~straight~. All straight recipes are set up in this file to remove the need for using the ~:straight~ keyword in each ~use-package~ form. In the same configuration file, explicitly list packages to ensure the use of built-in version over externally available one to avoid conflict.

*** ~init-loader~

The ~init-loader~ runs toward the end of =init.el=. The Emacs Lisp sources symlinked from =lisp/= to a directory named =init.d/<unit>/= are loaded and executed in order of priority based on file name, mostly ASCII.

Symlinking is managed by the =init.d/symlinks.sh= shell script:

#+begin_src shell
  ./init.d/symlinks.sh -r [unit]  # refresh symlinks in init.d/<unit>/
#+end_src

where the existence of =./init.d/unit-<unit>.sh= is prerequisite (if omitted, ~[unit]~ defaults to ~default~.) The unit-based modular design allows the user to configure Emacs differently on each invocation,based on the script =./init.d/unit-<unit>.sh=.

To use a specific unit, pass the unit name using the environment variable ~EMACS_INIT_LOADER_PROFILE~, e.g.,

#+begin_src shell
  EMACS_INIT_LOADER_PROFILE=<unit> emacs
#+end_src

*** ~desktop~ (Session Persistence)

Session persistence is available when =subsys-desktop= is loaded. Multiple sessions can be saved by providing a profile name using the environment variable ~EMACS_DESKTOP_PROFILE~ when invoking Emacs:

#+begin_src shell
  EMACS_DESKTOP_PROFILE=<profile> emacs
#+end_src

(This defaults to ~default~ when not explicitly provided.)

** Miscellaneous Topics

See the [[https://github.com/okomestudio/emacs.d/wiki][repository wiki]] for miscellaneous or faster changing topics.

* Installation

Clone the repository root to a path within the filesystem where Emacs can find the =init.el= file, e.g. =~/.config/emacs=.
