#!/usr/bin/env bash

# Maps priority to the modules found in the lisp directory
declare -A ptom
ptom["00"]="optimizations"
ptom["01"]="subsys-startup"
ptom["02"]="maj-minibuffer subsys-treesit"
ptom["03"]="subsys-flycheck subsys-text-match"
ptom["04"]="subsys-help subsys-buffer subsys-navigation subsys-projectile"
ptom["05"]="subsys-os-integration"
ptom["06"]="subsys-faces themes"
ptom["08"]="subsys-consult"
ptom["10"]="maj-org"
ptom["11"]="maj-org-roam"
ptom["20"]="subsys-ime"
ptom["22"]="subsys-writing-en"
ptom["30"]="subsys-auth subsys-term subsys-embark"
ptom["32"]="subsys-lsp subsys-eglot"
ptom["40"]="subsys-completion subsys-editing subsys-spelling subsys-git subsys-reference"
ptom["50"]="maj-text-mode"
ptom["52"]="maj-markdown maj-rst maj-yaml"
ptom["54"]="maj-conf-mode"
ptom["60"]="maj-prog-mode"
ptom["61"]="maj-polymode"
ptom["62"]="maj-c maj-css maj-docker maj-elisp maj-html maj-javascript maj-kotlin maj-python maj-rust maj-scala maj-sh maj-sql maj-web-mode"
ptom["64"]="maj-ansible subsys-drawing maj-graphviz maj-json maj-plantuml subsys-http"
ptom["70"]="subsys-doc-viewer subsys-ocr"
ptom["80"]="subsys-llm subsys-audio maj-eww subsys-game subsys-gnus subsys-map"
ptom["82"]="subsys-zotero"
ptom["86"]="maj-ibuffer"
ptom["90"]="subsys-readers subsys-treemacs subsys-weather"
ptom["91"]="maj-elfeed"
ptom["98"]="maj-dashboard"
ptom["linux-00"]="linux-gui"
